### PR TITLE
Update YouTube.ios.js to fit new 0.25 RN specifications

### PR DESCRIPTION
**Pull request by Mokto**
import React, Component from 'react' and not 'react-native' anymore

### CODE REVIEW

**Comment by paramaggarwal** [comment]
Hey @Mokto, would you be interesting in spear-heading work on this project? I am not using it anywhere anymore so it would be best if someone could now take care of it. What do you think?

**Comment by Mokto** [comment]
Hey @paramaggarwal,

With pleasure, I already manage [react-native-meteor](https://github.com/inProgress-team/react-native-meteor) and I like it.

I would also need npm access (my id is theo-mathieu) ;)

**Comment by paramaggarwal** [comment]
Ah, you need to delete/rename your fork first.

I have added you as a collaborator meanwhile. Also added you on npm. Thanks!

**Comment by Mokto** [comment]
Hey,

I did delete my forks. ;)

**Pull request merged**
