### PR TITLE
Added parameters : modestbranding, controls, showinfo

### PR DESCRIPTION
**Pull request by Mokto**
Hi,

Three more parameters are now available.

### CODE REVIEW

**Comment by Mokto** [comment]
REF #21

**Comment by paramaggarwal** [comment]
Didn't know that this existed. Thanks!

**Comment by Mokto** [comment]
A pleasure :)

@paramaggarwal I have one question regarding PR : I updated the README even if react-native-youtube is not pushed on NPM. Is it ok anyway ?

**Comment by paramaggarwal** [comment]
Pushed as `v0.4.0` to npm.

**Pull request merged**
